Add model for cisco iosxr logging module
ansible-network/resource_module_models pull request #142
Opened 2021-07-06 07:35 UTC by ashwini-mhatre

2021-07-07 06:18 UTC, rohitthakur2590 requested changes

2021-08-02 07:27 UTC, ashwini-mhatre commented on models/iosxr/logging_global/iosxr_logging_global.yaml
> +          file:
ack

2021-08-02 07:30 UTC, ashwini-mhatre commented on models/iosxr/logging_global/iosxr_logging_global.yaml
> +        description:
ack

2021-08-02 09:03 UTC, rohitthakur2590 approved these changes

2021-08-02 09:04 UTC, merged