Removed requirement description
ansible-network/resource_module_models pull request #186
Opened 2022-11-03 17:18 UTC by stalabi1

I removed the requirement for source_ip and evpn_nvo to be required together from the description.

2022-11-03 18:32 UTC, kerry-meyer requested changes
There is one more line to delete from the sonic_vxlans.yaml file (line 27). See the corresponding comment posted inline in the file diffs.

2022-11-03 18:32 UTC, kerry-meyer commented on models/enterprise_sonic/vxlans/sonic_vxlans.yaml
> -          - source_ip and evpn_nvo are required together.
Please also delete line 27 (the "required_together" dictionary element).

2022-11-03 21:38 UTC, kerry-meyer approved these changes
Thanks for updating this model.

Approved.

2022-11-04 06:02 UTC, NilashishC approved these changes

2022-11-04 06:02 UTC, merged