LLDP interface model definition
ansible-network/resource_module_models pull request #202
Opened 2023-03-03 04:47 UTC by divya-balasubramania

2023-04-02 15:04 UTC, ArunSaravananBalachandran requested changes

2023-04-02 15:04 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/sonic_lldp_interfaces.yml
> +                type: str
Please change the type to `bool` for enabling or disabling the options.

2023-04-02 15:04 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/sonic_lldp_interfaces.yml
> +                - 'power-management'
Please change "tlv_select" to `list` and "power_management" as one of its sub-options of type `bool`, similar to structure of "med_tlv_select"

2023-05-04 07:03 UTC, ArunSaravananBalachandran requested changes

2023-05-04 07:03 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/deleted_example_02.txt
> +          network_policy: True
Please include the name of the interface to be configured.

2023-05-04 07:03 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/sonic_lldp_interfaces.yml
> +            elements: dict
Please change type to 'dict'.

2023-05-04 07:03 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/sonic_lldp_interfaces.yml
> +            elements: dict
Please change type to 'dict'.

2023-05-04 07:03 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/sonic_lldp_interfaces.yml
> +             elements: dict
Please change type to 'dict'.

2023-05-17 12:24 UTC, ArunSaravananBalachandran requested changes
Please move the delete all example to 'deleted_example_04.txt' and include a new example in 'deleted_example_03.txt' to showcase deletion of all non-default LLDP configurations in an interface by specifying only the name of that interface.

Also, please ensure that all the bool values in the examples are in the format `true`/`false`.

2023-05-17 12:24 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/deleted_example_01.txt
> +  - name: Delete LLDP interface configurations
```suggestion
# sonic#

  - name: Delete LLDP interface configurations
```

2023-05-17 12:24 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/deleted_example_02.txt
Please update the after and before state to list the same set of interfaces.

2023-05-17 12:24 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/deleted_example_03.txt
> +  - name: Delete all LLDP Interface configuration
```suggestion
# sonic#

  - name: Delete all LLDP Interface configurations
```

2023-05-17 12:24 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/deleted_example_03.txt
Please list multiple interfaces in before and after state, to show the deletion of non-default LLDP configurations in all the interfaces with an empty config.

2023-05-17 12:24 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/merged_example_01.txt
Please update the after and before state to list the same set of interfaces.

2023-05-17 12:24 UTC, ArunSaravananBalachandran commented on models/enterprise_sonic/lldp_interfaces/sonic_lldp_interfaces.yml
> +            required: True
```suggestion
            required: true
```

2023-05-23 05:48 UTC, divya-balasubramania commented on models/enterprise_sonic/lldp_interfaces/deleted_example_01.txt
> +  - name: Delete LLDP interface configurations
done

2023-05-23 05:48 UTC, divya-balasubramania commented on models/enterprise_sonic/lldp_interfaces/deleted_example_02.txt
done

2023-05-30 11:57 UTC, ArunSaravananBalachandran approved these changes

2023-08-30 06:07 UTC, merged