SONiC DHCP Snooping model definition
ansible-network/resource_module_models pull request #227
Opened 2023-07-07 20:17 UTC by simon-nathans

The DHCP Snooping model definition for SONiC.

2023-07-10 20:17 UTC, kerry-meyer requested changes
The structure and content of this model look good.

I have posted a few comments requesting minor changes and also am requesting the addition of a global "per-afi" attribute to indicate the "enabled" state for DHCP snooping on that AFI. (Please let me know if there is some reason why this is not needed.)

2023-07-10 20:17 UTC, kerry-meyer commented on models/enterprise_sonic/dhcp_snooping/dhcp_snooping.yaml
> +        afis:
The "afis" dict should also contain an "enabled" bool for each AFI.

2023-07-11 04:56 UTC, kerry-meyer approved these changes
Thanks for making the additional requested changes.

Approved.

2023-07-11 17:35 UTC, simon-nathans commented
Closing because commits were not made on a new branch. Will open a new PR

2023-07-11 17:35 UTC, closed without merging